server:
  port: 9999
spring:
  application:
    name: spring-security-demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_security_demo?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 2
mybatis:
  check-config-location: true
  mapper-locations: classpath*:com/xiao/dao/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
logging:
  file:
    path: ./logs
  level:
    root: info
    com.geshu.pts: info
    org.springframework: warn