spring:
  application:
    name: spring-security-demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/police_test_system?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9999
mybatis:
  check-config-location: true
  mapper-locations: classpath*:com/xiao/dao/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl